/*
-- Query: SELECT * FROM tblStage
LIMIT 0, 1000

-- Date: 2017-11-16 09:53
*/
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (1,'DESCRIPTIONYVZTX','competenceRLNCQ','plein',34,NULL,22,'2017-11-08','2018-07-02',NULL,NULL,NULL,101,51,1,131);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (2,'DESCRIPTIONFVDAF','competencePAREJ','plein',26,NULL,39,'2017-07-12','2018-09-09',NULL,NULL,NULL,102,52,2,132);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (3,'DESCRIPTIONFHBPY','competenceVXWEB','plein',24,NULL,34,'2017-01-26','2018-06-21',NULL,NULL,NULL,103,53,3,133);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (4,'DESCRIPTIONUDMAO','competenceQMXFI','plein',32,NULL,17,'2017-03-18','2018-05-29',NULL,NULL,NULL,104,54,4,134);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (5,'DESCRIPTIONDSEPZ','competencePNYNW','plein',21,NULL,14,'2017-10-27','2018-03-08',NULL,NULL,NULL,105,55,5,135);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (6,'DESCRIPTIONKRQNN','competenceLZEGE','plein',28,NULL,27,'2017-06-02','2018-07-06',NULL,NULL,NULL,106,56,6,131);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (7,'DESCRIPTIONHRJIZ','competenceGKULM','plein',33,NULL,10,'2017-09-26','2018-09-28',NULL,NULL,NULL,107,57,7,132);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (8,'DESCRIPTIONPBHUP','competenceRHKOZ','plein',39,NULL,34,'2017-07-24','2018-10-10',NULL,NULL,NULL,108,58,8,133);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (9,'DESCRIPTIONAYDGJ','competenceIFTMF','plein',13,NULL,28,'2017-07-25','2018-02-11',NULL,NULL,NULL,109,59,9,134);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (10,'DESCRIPTIONOPEHB','competenceMXBWH','plein',39,NULL,28,'2017-12-03','2018-03-15',NULL,NULL,NULL,110,60,10,135);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (11,'DESCRIPTIONVTRXL','competencePRMJL','plein',19,NULL,24,'2017-11-18','2018-11-22',NULL,NULL,NULL,111,61,11,131);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (12,'DESCRIPTIONDENPN','competenceQKLNC','plein',29,NULL,10,'2017-11-08','2018-05-15',NULL,NULL,NULL,112,62,12,132);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (13,'DESCRIPTIONJPKBB','competenceTCHGX','plein',28,NULL,10,'2017-02-22','2018-07-02',NULL,NULL,NULL,113,63,13,133);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (14,'DESCRIPTIONCETQP','competenceQTMXP','plein',33,NULL,25,'2017-02-25','2018-11-14',NULL,NULL,NULL,114,64,14,134);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (15,'DESCRIPTIONBTYIY','competenceTUDFT','plein',29,NULL,16,'2017-12-17','2018-12-03',NULL,NULL,NULL,115,65,15,135);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (16,'DESCRIPTIONAXXXI','competencePEZBN','plein',21,NULL,28,'2017-05-18','2018-02-23',NULL,NULL,NULL,116,66,16,131);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (17,'DESCRIPTIONHAZNF','competenceSHJEJ','plein',20,NULL,40,'2017-09-09','2018-07-03',NULL,NULL,NULL,117,67,17,132);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (18,'DESCRIPTIONDERZF','competenceRIBEO','plein',40,NULL,25,'2017-12-29','2018-01-02',NULL,NULL,NULL,118,68,18,133);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (19,'DESCRIPTIONFHKJD','competenceBZPPX','plein',10,NULL,26,'2017-09-16','2018-03-17',NULL,NULL,NULL,119,69,19,134);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (20,'DESCRIPTIONZQWBJ','competenceDSYTJ','plein',16,NULL,20,'2017-03-14','2018-11-23',NULL,NULL,NULL,120,70,20,135);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (21,'DESCRIPTIONCVWHH','competenceKMHOJ','plein',17,NULL,36,'2017-01-15','2018-08-08',NULL,NULL,NULL,101,71,21,131);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (22,'DESCRIPTIONOXRQJ','competenceLXQUX','plein',26,NULL,23,'2017-11-16','2018-03-23',NULL,NULL,NULL,102,72,22,132);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (23,'DESCRIPTIONXSYBG','competenceKJNIH','plein',28,NULL,40,'2017-07-23','2018-02-18',NULL,NULL,NULL,103,73,23,133);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (24,'DESCRIPTIONZDCSR','competenceDUVPY','plein',26,NULL,29,'2017-02-07','2018-04-18',NULL,NULL,NULL,104,74,24,134);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (25,'DESCRIPTIONCUFSX','competenceUORYE','plein',21,NULL,21,'2017-06-02','2018-06-20',NULL,NULL,NULL,105,75,25,135);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (26,'DESCRIPTIONIEDPR','competenceAPPHA','plein',12,NULL,30,'2017-02-19','2018-09-22',NULL,NULL,NULL,106,76,26,131);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (27,'DESCRIPTIONWBEDZ','competenceBETRK','plein',27,NULL,39,'2017-04-14','2018-07-13',NULL,NULL,NULL,107,77,27,132);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (28,'DESCRIPTIONZVBBU','competencePJKKD','plein',24,NULL,38,'2017-12-12','2018-02-01',NULL,NULL,NULL,108,78,28,133);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (29,'DESCRIPTIONKYHSZ','competenceIWXUT','partiel',18,NULL,16,'2017-10-12','2018-08-08',NULL,NULL,NULL,109,79,29,134);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (30,'DESCRIPTIONVPTSS','competenceCMWWE','partiel',34,NULL,34,'2017-05-14','2018-07-03',NULL,NULL,NULL,110,51,30,135);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (31,'DESCRIPTIONACRPT','competenceWQDCP','partiel',23,NULL,10,'2017-10-09','2018-08-28',NULL,NULL,NULL,111,52,31,131);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (32,'DESCRIPTIONIPTEX','competenceNRFTI','partiel',25,NULL,22,'2017-11-24','2018-09-22',NULL,NULL,NULL,112,53,32,132);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (33,'DESCRIPTIONBDXHL','competenceCDFWB','partiel',18,NULL,40,'2017-01-23','2018-12-27',NULL,NULL,NULL,113,54,33,133);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (34,'DESCRIPTIONCKMPR','competenceBVDWX','partiel',22,NULL,38,'2017-07-04','2018-04-18',NULL,NULL,NULL,114,55,34,134);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (35,'DESCRIPTIONHRWCG','competenceFCEKZ','partiel',20,NULL,26,'2017-05-25','2018-10-24',NULL,NULL,NULL,115,56,35,135);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (36,'DESCRIPTIONCGTKL','competenceRLPDR','partiel',32,NULL,14,'2017-10-15','2018-02-16',NULL,NULL,NULL,116,57,36,131);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (37,'DESCRIPTIONGYGBP','competenceZPWGZ','partiel',34,NULL,35,'2017-03-20','2018-11-22',NULL,NULL,NULL,117,58,37,132);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (38,'DESCRIPTIONOQXMX','competenceOETNK','partiel',39,NULL,16,'2017-05-16','2018-06-03',NULL,NULL,NULL,118,59,38,133);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (39,'DESCRIPTIONQTVNT','competenceRCRFY','partiel',32,NULL,37,'2017-07-01','2018-12-30',NULL,NULL,NULL,119,60,39,134);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (40,'DESCRIPTIONLMEEC','competenceICSED','partiel',23,NULL,30,'2017-12-21','2018-08-25',NULL,NULL,NULL,120,61,40,135);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (41,'DESCRIPTIONFPDJI','competenceQMLBA','partiel',35,NULL,15,'2017-06-13','2018-01-12',NULL,NULL,NULL,101,62,41,131);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (42,'DESCRIPTIONBCMGH','competenceZLAWG','partiel',24,NULL,34,'2017-01-08','2018-10-18',NULL,NULL,NULL,102,63,42,132);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (43,'DESCRIPTIONYQEVG','competenceZSRKK','partiel',23,NULL,15,'2017-09-24','2018-03-05',NULL,NULL,NULL,103,64,43,133);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (44,'DESCRIPTIONNDEXT','competenceUKEJO','partiel',28,NULL,21,'2017-09-29','2018-07-26',NULL,NULL,NULL,104,65,44,134);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (45,'DESCRIPTIONPWYNG','competenceGFEQY','partiel',15,NULL,19,'2017-09-09','2018-02-27',NULL,NULL,NULL,105,66,45,135);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (46,'DESCRIPTIONVHDUW','competenceIGHPD','partiel',35,NULL,24,'2017-12-19','2018-05-01',NULL,NULL,NULL,106,67,46,131);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (47,'DESCRIPTIONAMKWW','competenceJIZXJ','partiel',24,NULL,39,'2017-06-15','2018-10-17',NULL,NULL,NULL,107,68,47,132);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (48,'DESCRIPTIONIYWRD','competenceAPIRL','partiel',18,NULL,37,'2017-02-04','2018-03-07',NULL,NULL,NULL,108,69,48,133);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (49,'DESCRIPTIONRUUSC','competenceCVPUF','partiel',30,NULL,24,'2017-02-21','2018-03-16',NULL,NULL,NULL,109,70,49,134);
INSERT INTO `tblStage` (`Id`,`DescriptionStage`,`CompetenceRecherche`,`HoraireTravail`,`NbHeureSemaine`,`Remunere`,`SalaireHoraire`,`DateDebut`,`DateFin`,`LettreEntenteVide`,`LettreEntenteSignee`,`OffreStage`,`IdResponsable`,`IdSuperviseur`,`IdStagiaire`,`IdEnseignant`) VALUES (50,'DESCRIPTIONTIVKG','competenceWDQCD','partiel',35,NULL,22,'2017-01-09','2018-03-30',NULL,NULL,NULL,110,71,50,135);
