/*
-- Query: SELECT * FROM tblutilisateur
LIMIT 0, 1000

-- Date: 2017-10-13 03:41
*/
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (1,'Tremblay.Olimpia@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (2,'Bouchard.Olga@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (3,'Duchesne.Leonarda@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (4,'Poirier.Kelly@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (5,'Jean.Cyril@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (6,'Gilbert.Rufina@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (7,'Tremblay.Torri@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (8,'Bouchard.Cliff@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (9,'Duchesne.Kyoko@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (10,'Poirier.Elvie@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (11,'Jean.Barbra@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (12,'Gilbert.Graig@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (13,'Tremblay.Pamala@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (14,'Bouchard.Jermaine@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (15,'Duchesne.Chau@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (16,'Poirier.Almeta@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (17,'Jean.Denita@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (18,'Gilbert.Larita@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (19,'Tremblay.Bridgette@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (20,'Bouchard.Sherika@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (21,'Duchesne.Monroe@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (22,'Poirier.Liliana@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (23,'Jean.Lavona@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (24,'Gilbert.Manda@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (25,'Tremblay.Conchita@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (26,'Bouchard.Emanuel@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (27,'Duchesne.Celestine@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (28,'Poirier.Rikki@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (29,'Jean.Jacque@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (30,'Gilbert.Kelle@etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (31,'Tremblay.Arlene  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (32,'Bouchard.Enoch  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (33,'Duchesne.Marsha  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (34,'Poirier.Jeffrey  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (35,'Jean.Jaqueline  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (36,'Gilbert.Reita  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (37,'Tremblay.Alix  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (38,'Bouchard.Bruce  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (39,'Duchesne.Nickie  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (40,'Poirier.Jesusita  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (41,'Jean.Marylou  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (42,'Gilbert.Mariam  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (43,'Tremblay.Dorine  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (44,'Bouchard.Wiley  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (45,'Duchesne.Julissa  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (46,'Poirier.Nery  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (47,'Jean.Rena  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (48,'Gilbert.Olene  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (49,'Tremblay.Arlen  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (50,'Bouchard.Chassidy  @etu.cegepjonquiere.ca','motpasse',5);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (51,'Lovely@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (52,'Flippant@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (53,'Picayune@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (54,'Well-made@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (55,'Blushing@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (56,'Astonishing@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (57,'Stimulating@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (58,'Cynical@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (59,'Sulky@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (60,'Silent@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (61,'Voiceless@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (62,'Fresh@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (63,'Upset@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (64,'Well-groomed@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (65,'Excited@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (66,'Macho@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (67,'Loving@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (68,'Elastic@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (69,'Spicy@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (70,'Drab@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (71,'Noxious@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (72,'Fancy@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (73,'Rude@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (74,'Sophisticated@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (75,'Plucky@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (76,'Rough@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (77,'Elated@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (78,'Rightful@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (79,'Humorous@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (80,'Cut@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (81,'Disgusting@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (82,'Shaggy@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (83,'Straight@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (84,'Pink@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (85,'Furtive@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (86,'Tasty@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (87,'Selective@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (88,'Grubby@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (89,'Cagey@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (90,'Aspiring@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (91,'Interesting@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (92,'Hurried@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (93,'Innocent@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (94,'Ugly@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (95,'Rambunctious@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (96,'Scary@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (97,'Icky@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (98,'Bite-sized@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (99,'Hard@gmail.com','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (100,'tremblay.Ernie@Hotmail.ca','motpasse',4);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (101,'bouchard.Sanford@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (102,'poirier.Les@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (103,'sioud.Leandro@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (104,'tremblay.Nelson@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (105,'bouchard.Harvey@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (106,'poirier.Malcolm@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (107,'sioud.Colton@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (108,'tremblay.Neal@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (109,'bouchard.Allen@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (110,'poirier.Dylan@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (111,'sioud.Weston@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (112,'tremblay.Doug@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (113,'bouchard.Shawn@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (114,'poirier.Dominick@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (115,'sioud.Mohammad@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (116,'tremblay.Donte@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (117,'bouchard.Brian@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (118,'poirier.Glen@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (119,'sioud.Galen@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (120,'tremblay.Scot@Hotmail.ca','motpasse',2);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (121,'bouchard.Gerry@Hotmail.ca','motpasse',1);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (122,'poirier.Claudio@Hotmail.ca','motpasse',1);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (123,'sioud.Lyman@Hotmail.ca','motpasse',1);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (124,'tremblay.Emile@Hotmail.ca','motpasse',1);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (125,'bouchard.Monte@Hotmail.ca','motpasse',1);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (126,'poirier.Louie@Hotmail.ca','motpasse',1);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (127,'sioud.Preston@Hotmail.ca','motpasse',1);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (128,'tremblay.Coleman@Hotmail.ca','motpasse',1);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (129,'bouchard.Marcelino@Hotmail.ca','motpasse',1);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (130,'poirier.Elden@Hotmail.ca','motpasse',1);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (131,'sioud.Randell@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (132,'tremblay.Dane@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (133,'bouchard.Clinton@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (134,'poirier.Hubert@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (135,'sioud.Jean@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (136,'tremblay.Hong@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (137,'bouchard.Jame@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (138,'poirier.Hugo@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (139,'sioud.Vito@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (140,'tremblay.Eldridge@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (141,'bouchard.Agustin@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (142,'poirier.Sonny@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (143,'sioud.Ward@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (144,'tremblay.Grant@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (145,'bouchard.Dana@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (146,'poirier.Larry@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (147,'sioud.Stefan@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (148,'tremblay.Marcel@Hotmail.ca','motpasse',3);
INSERT INTO `tblUtilisateur` (`Id`,`Courriel`,`MotDePasse`,`IdRole`) VALUES (149,'bouchard.Manual@Hotmail.ca','motpasse',3);
