/*
-- Query: SELECT * FROM bdprojet_equipe2v2.tblEntreprise
LIMIT 0, 1000

-- Date: 2017-09-18 22:16
*/
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (1,'BanTheB','(394) 202-8610','4205','Bridl','Bangkok','QC','10956','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (2,'NaiBent','(999) 523-1080','7179','Wood','Nairobi','ON','7960','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (3,'BeiUnsu','(881) 230-7006','8350','Monro','Beijing','MA','77904','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (4,'DhaDeco','(817) 975-5623','7317','Cathe','Dhaka','AL','32904','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (5,'BanDisc','(106) 218-4313','8764','Madis','Bangalore','BC','29710','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (6,'MexRoma','(789) 858-4542','8906','Chest','Mexico City','NB','97124','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (7,'IstPeti','(691) 509-4840','7866','Cemet','Istanbul','ON','11572','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (8,'JohVers','(785) 459-1547','5058','River','Johannesburg','QC','4401','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (9,'PyoEner','(412) 959-1915','2602','Winds','Pyongyang','NB','11010','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (10,'LahAbra','(148) 862-4114','6474','Deerf','Lahore','MA','11554','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (11,'JakUnhe','(473) 401-6167','6455','Hill','Jakarta','BC','2864','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (12,'YanRoas','(946) 163-6382','1133','Cedar','Yangon','QC','33160','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (13,'TiaVigo','(968) 746-0811','9796','Locus','Tianjin','AL','27302','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (14,'Ho Boil','(380) 236-0580','9062','8th A','Ho Chi Minh City','ON','0102A','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (15,'ShaColo','(508) 684-3506','3781','Ridge','Shanghai','NB','44663','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (16,'DonObse','(772) 919-8834','1504','Highl','Dongguan','QC','5211C','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (17,'DelSpec','(568) 416-5712','6152','Primr','Delhi','NB','31204','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (18,'JaiMeat','(210) 266-3958','2559','Amher','Jaipur','MA','20815','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (19,'GuaUnru','(801) 283-4613','9867','Cherr','Guangzhou','BC','60047','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (20,'HanWate','(926) 322-8197','1671','Durha','Hanoi','AL','33040','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (21,'SheSmar','(959) 393-0840','1839','Mulbe','Shenzhen','QC','11725','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (22,'AddNorm','(234) 133-0090','5865','Overl','Addis Ababa','ON','16506','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (23,'HonRamp','(638) 109-3878','3701','Andov','Hong Kong','MA','19020','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (24,'JedPerf','(117) 367-1230','7341','5th S','Jeddah','NB','60201','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (25,'AhmSlim','(545) 729-9971','1923','Adams','Ahmedabad','AL','51501','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (26,'MosChiv','(540) 520-6850','2364','Main','Moscow','QC','44122','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (27,'TehSudd','(652) 160-4165','6835','Divis','Tehran','ON','13440','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (28,'Cudd','(238) 213-1521','5485','Cobbl','','NB','16001','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (29,'MadHuge','(126) 824-3280','5295','Route','Madrid','MA','29550','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (30,'SurWrat','(640) 317-7482','9669','Everg','Surat','ON','46383','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (31,'SanRasp','(386) 720-7754','6148','Hanov','Santiago','AL','6051','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (32,'DurLame','(821) 309-9772','6812','Route','Durban','NB','11776','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (33,'HydQuai','(574) 301-2789','2701','Cardi','Hyderabad','BC','6111','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (34,'BagCold','(364) 828-0003','5879','Route','Baghdad','QC','43026','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (35,'BusGuil','(463) 352-3104','1613','Brook','Busan','ON','23320','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (36,'NaiThic','(872) 761-9930','2254','Rose','Nairobi','NB','90008','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (37,'SheLivi','(655) 256-7667','7909','East','Shenyang','ON','4240','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (38,'CheNebu','(688) 488-6436','3892','Canal','Chennai','NB','44133','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (39,'RiyYiel','(979) 804-2989','5618','Myrtl','Riyadh','MA','1851','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (40,'AbiMyst','(512) 726-0509','9745','Hamil','Abidjan','BC','46901','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (41,'AnkSubd','(634) 958-7518','1399','Orang','Ankara','ON','34203','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (42,'CasWiry','(560) 337-9093','2587','Smith','Casablanca','QC','46060','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (43,'BerBrig','(947) 767-6257','4583','8th S','Berlin','NB','72209','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (44,'BanToot','(759) 407-7378','8734','High','Bangkok','MA','41017','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (45,'NewFar-','(322) 157-3038','7875','Lafay','New Taipei City','ON','71730','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (46,'YokAbso','(506) 460-6300','4597','Ashle','Yokohama','AL','91762','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (47,'NewDisi','(835) 755-2430','6185','Creek','New York City','QC','60031','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (48,'LosApat','(543) 170-6043','6098','Frank','Los Angeles','MA','29910','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (49,'JakStin','(349) 919-6016','3996','Taylo','Jakarta','MA','32765','','',NULL);
INSERT INTO `tblEntreprise` (`Id`,`CourrielEntreprise`,`Nom`,`NumTel`,`NumCivique`,`Rue`,`Ville`,`Province`,`CodePostal`,`Logo`,`tagEntreprise`) VALUES (50,'TiaIncr','(120) 850-8973','7710','Route','Tianjin','ON','60056','','',NULL);
