/*
-- Query: SELECT * FROM tblstagiaire
LIMIT 0, 1000

-- Date: 2017-09-24 23:43
*/
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (1,'Tremblay.Olimpia@etu.cegepjonquiere.ca','Tremblay','Olimpia','(418) 695-1924','(418) 695-1974','Tremblay.Olimpia@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (2,'Bouchard.Olga@etu.cegepjonquiere.ca','Bouchard','Olga','(418) 695-1925','(418) 695-1975','Bouchard.Olga@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (3,'Duchesne.Leonarda@etu.cegepjonquiere.ca','Duchesne','Leonarda','(418) 695-1926','(418) 695-1976','Duchesne.Leonarda@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (4,'Poirier.Kelly@etu.cegepjonquiere.ca','Poirier','Kelly','(418) 695-1927','(418) 695-1977','Poirier.Kelly@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (5,'Jean.Cyril@etu.cegepjonquiere.ca','Jean','Cyril','(418) 695-1928','(418) 695-1978','Jean.Cyril@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (6,'Gilbert.Rufina@etu.cegepjonquiere.ca','Gilbert','Rufina','(418) 695-1929','(418) 695-1979','Gilbert.Rufina@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (7,'Tremblay.Torri@etu.cegepjonquiere.ca','Tremblay','Torri','(418) 695-1930','(418) 695-1980','Tremblay.Torri@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (8,'Bouchard.Cliff@etu.cegepjonquiere.ca','Bouchard','Cliff','(418) 695-1931','(418) 695-1981','Bouchard.Cliff@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (9,'Duchesne.Kyoko@etu.cegepjonquiere.ca','Duchesne','Kyoko','(418) 695-1932','(418) 695-1982','Duchesne.Kyoko@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (10,'Poirier.Elvie@etu.cegepjonquiere.ca','Poirier','Elvie','(418) 695-1933','(418) 695-1983','Poirier.Elvie@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (11,'Jean.Barbra@etu.cegepjonquiere.ca','Jean','Barbra','(418) 695-1934','(418) 695-1984','Jean.Barbra@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (12,'Gilbert.Graig@etu.cegepjonquiere.ca','Gilbert','Graig','(418) 695-1935','(418) 695-1985','Gilbert.Graig@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (13,'Tremblay.Pamala@etu.cegepjonquiere.ca','Tremblay','Pamala','(418) 695-1936','(418) 695-1986','Tremblay.Pamala@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (14,'Bouchard.Jermaine@etu.cegepjonquiere.ca','Bouchard','Jermaine','(418) 695-1937','(418) 695-1987','Bouchard.Jermaine@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (15,'Duchesne.Chau@etu.cegepjonquiere.ca','Duchesne','Chau','(418) 695-1938','(418) 695-1988','Duchesne.Chau@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (16,'Poirier.Almeta@etu.cegepjonquiere.ca','Poirier','Almeta','(418) 695-1939','(418) 695-1989','Poirier.Almeta@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (17,'Jean.Denita@etu.cegepjonquiere.ca','Jean','Denita','(418) 695-1940','(418) 695-1990','Jean.Denita@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (18,'Gilbert.Larita@etu.cegepjonquiere.ca','Gilbert','Larita','(418) 695-1941','(418) 695-1991','Gilbert.Larita@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (19,'Tremblay.Bridgette@etu.cegepjonquiere.ca','Tremblay','Bridgette','(418) 695-1942','(418) 695-1992','Tremblay.Bridgette@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (20,'Bouchard.Sherika@etu.cegepjonquiere.ca','Bouchard','Sherika','(418) 695-1943','(418) 695-1993','Bouchard.Sherika@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (21,'Duchesne.Monroe@etu.cegepjonquiere.ca','Duchesne','Monroe','(418) 695-1944','(418) 695-1994','Duchesne.Monroe@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (22,'Poirier.Liliana@etu.cegepjonquiere.ca','Poirier','Liliana','(418) 695-1945','(418) 695-1995','Poirier.Liliana@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (23,'Jean.Lavona@etu.cegepjonquiere.ca','Jean','Lavona','(418) 695-1946','(418) 695-1996','Jean.Lavona@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (24,'Gilbert.Manda@etu.cegepjonquiere.ca','Gilbert','Manda','(418) 695-1947','(418) 695-1997','Gilbert.Manda@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (25,'Tremblay.Conchita@etu.cegepjonquiere.ca','Tremblay','Conchita','(418) 695-1948','(418) 695-1998','Tremblay.Conchita@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (26,'Bouchard.Emanuel@etu.cegepjonquiere.ca','Bouchard','Emanuel','(418) 695-1949','(418) 695-1999','Bouchard.Emanuel@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (27,'Duchesne.Celestine@etu.cegepjonquiere.ca','Duchesne','Celestine','(418) 695-1950','(418) 695-2000','Duchesne.Celestine@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (28,'Poirier.Rikki@etu.cegepjonquiere.ca','Poirier','Rikki','(418) 695-1951','(418) 695-2001','Poirier.Rikki@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (29,'Jean.Jacque@etu.cegepjonquiere.ca','Jean','Jacque','(418) 695-1952','(418) 695-2002','Jean.Jacque@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (30,'Gilbert.Kelle@etu.cegepjonquiere.ca','Gilbert','Kelle','(418) 695-1953','(418) 695-2003','Gilbert.Kelle@hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (31,'Tremblay.Arlene  @etu.cegepjonquiere.ca','Tremblay','Arlene  ','(418) 695-1954','(418) 695-2004','Tremblay.Arlene  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (32,'Bouchard.Enoch  @etu.cegepjonquiere.ca','Bouchard','Enoch  ','(418) 695-1955','(418) 695-2005','Bouchard.Enoch  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (33,'Duchesne.Marsha  @etu.cegepjonquiere.ca','Duchesne','Marsha  ','(418) 695-1956','(418) 695-2006','Duchesne.Marsha  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (34,'Poirier.Jeffrey  @etu.cegepjonquiere.ca','Poirier','Jeffrey  ','(418) 695-1957','(418) 695-2007','Poirier.Jeffrey  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (35,'Jean.Jaqueline  @etu.cegepjonquiere.ca','Jean','Jaqueline  ','(418) 695-1958','(418) 695-2008','Jean.Jaqueline  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (36,'Gilbert.Reita  @etu.cegepjonquiere.ca','Gilbert','Reita  ','(418) 695-1959','(418) 695-2009','Gilbert.Reita  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (37,'Tremblay.Alix  @etu.cegepjonquiere.ca','Tremblay','Alix  ','(418) 695-1960','(418) 695-2010','Tremblay.Alix  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (38,'Bouchard.Bruce  @etu.cegepjonquiere.ca','Bouchard','Bruce  ','(418) 695-1961','(418) 695-2011','Bouchard.Bruce  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (39,'Duchesne.Nickie  @etu.cegepjonquiere.ca','Duchesne','Nickie  ','(418) 695-1962','(418) 695-2012','Duchesne.Nickie  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (40,'Poirier.Jesusita  @etu.cegepjonquiere.ca','Poirier','Jesusita  ','(418) 695-1963','(418) 695-2013','Poirier.Jesusita  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (41,'Jean.Marylou  @etu.cegepjonquiere.ca','Jean','Marylou  ','(418) 695-1964','(418) 695-2014','Jean.Marylou  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (42,'Gilbert.Mariam  @etu.cegepjonquiere.ca','Gilbert','Mariam  ','(418) 695-1965','(418) 695-2015','Gilbert.Mariam  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (43,'Tremblay.Dorine  @etu.cegepjonquiere.ca','Tremblay','Dorine  ','(418) 695-1966','(418) 695-2016','Tremblay.Dorine  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (44,'Bouchard.Wiley  @etu.cegepjonquiere.ca','Bouchard','Wiley  ','(418) 695-1967','(418) 695-2017','Bouchard.Wiley  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (45,'Duchesne.Julissa  @etu.cegepjonquiere.ca','Duchesne','Julissa  ','(418) 695-1968','(418) 695-2018','Duchesne.Julissa  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (46,'Poirier.Nery  @etu.cegepjonquiere.ca','Poirier','Nery  ','(418) 695-1969','(418) 695-2019','Poirier.Nery  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (47,'Jean.Rena  @etu.cegepjonquiere.ca','Jean','Rena  ','(418) 695-1970','(418) 695-2020','Jean.Rena  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (48,'Gilbert.Olene  @etu.cegepjonquiere.ca','Gilbert','Olene  ','(418) 695-1971','(418) 695-2021','Gilbert.Olene  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (49,'Tremblay.Arlen  @etu.cegepjonquiere.ca','Tremblay','Arlen  ','(418) 695-1972','(418) 695-2022','Tremblay.Arlen  @hotmail.com\r',NULL,NULL,NULL,NULL);
INSERT INTO `tblStagiaire` (`Id`,`CourrielScolaire`,`Nom`,`Prenom`,`NumTelPersonnel`,`NumTelMaison`,`CourrielPersonnel`,`NumTelEntreprise`,`Poste`,`CourrielEntreprise`,`IdStage`) VALUES (50,'Bouchard.Chassidy  @etu.cegepjonquiere.ca','Bouchard','Chassidy  ','(418) 695-1973','(418) 695-2023','Bouchard.Chassidy  @hotmail.com\r',NULL,NULL,NULL,NULL);
